---
kind: pipeline
type: kubernetes
name: backend

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    image: nhyne/rust-musl-builder-sccache:nightly-2019-07-08
    user: root
    commands:
      - sudo cp -R ./* /home/rust/src
      - sudo chown -R rust:rust /home/rust/src
      - cd /home/rust/src
      - sccache --start-server
      - cargo test
      - sccache -s
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: build_cache_aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: build_cache_aws_secret_access_key
      RUSTC_WRAPPER: sccache
      SCCACHE_BUCKET: nhyne-build-cache
    when:
      changeset:
        includes: [ src/**/* ]

  - name: docker-archiver-api
    image: plugins/docker
    settings:
      auto_tag: true
      password:
        from_secret: docker_password
      repo: nhyne/archiver-api
      username:
        from_secret: docker_username
    when:
      event: [ tag ]

  - name: docker-diesel-cli
    image: plugins/docker
    settings:
      auto_tag: true
      password:
        from_secret: docker_password
      repo: nhyne/diesel-cli
      username:
        from_secret: docker_username
    when:
      changeset:
        includes: [ DieselDockerfile ]

  - name: docker-sccache
    image: plugins/docker
    settings:
      auto_tag: true
      password:
        from_secret: docker_password
      repo: nhyne/rust-musl-builder-sccache
      username:
        from_secret: docker_username
    when:
      changeset:
        includes: [ SccacheDockerfile ]

trigger:
  event:
    - push
    - pull_request
    - tag
