[global]
port = 8001
[global.tls]
certs = "/etc/ssl/certs/nhyne-dev-cert.pem"
key = "/etc/ssl/certs/nhyne-dev-key.pem"

[staging]
address = "0.0.0.0"

[production]
address = "0.0.0.0"

[development]
address = "127.0.0.1"

